In [30]:
import pandas as pd
import numpy as np
import os
from pandas import Series, DataFrame
group_train = pd.read_csv("C:\\Users\\karis\\NewGroup_data.txt", sep="\t", header = None, names= ['phrase_id', 'review', 'group_id'])
group_train.head()

phrase_id                                             review  group_id
0          1  ['From: mathew <mathew@mantis.co.uk>\n', 'Subj...         0
1          2  ['From: mathew <mathew@mantis.co.uk>\n', 'Subj...         0
2          3  ['From: I3150101@dbstu1.rz.tu-bs.de (Benedikt ...         0
3          4  ['From: mathew <mathew@mantis.co.uk>\n', 'Subj...         0
4          5  ['From: strom@Watson.Ibm.Com (Rob Strom)\n', '...         0

In [31]:
group_test = pd.read_csv("C:\\Users\\karis\\NewGroup_data_test.txt", sep="\t", header = None, names= ['phrase_id', 'review', 'group_id'])
group_test.head()

phrase_id                                             review  group_id
0          1  ['From: decay@cbnewsj.cb.att.com (dean.kaflowi...         0
1          2  ['From: cfaehl@vesta.unm.edu (Chris Faehl)\n',...         0
2          3  ['From: mathew <mathew@mantis.co.uk>\n', 'Subj...         0
3          4  ['From: dps@nasa.kodak.com (Dan Schaertel,,,)\...         0
4          5  ['From: halat@panther.bears (Jim Halat)\n', 'S...         0

In [33]:
# maping cateogories to train dataframe

group_train['category'] = group_train.group_id.map({0:'alt', 1:'comp',2:'comp', 3:'comp', 4:'comp',5:'comp',6:'misc', 7:'rec', 8:'rec',9:'rec', 10:'rec', 11:'sci',
                                    12:'sci', 13:'sci', 14:'sci', 15:'religion', 
                                    16:'politics', 17:'politics', 18:'politics', 19:'religion'})

# maping cateogories to test dataframe

group_test['category'] = group_test.group_id.map({0:'alt', 1:'comp',2:'comp', 3:'comp', 4:'comp',5:'comp',6:'misc', 7:'rec', 8:'rec',9:'rec', 10:'rec', 11:'sci',
                                    12:'sci', 13:'sci', 14:'sci', 15:'religion', 
                                    16:'politics', 17:'politics', 18:'politics', 19:'religion'})

group_test.shape

(7532, 4)

In [34]:
# selecting categories 
group_train_category = group_train[(group_train.category == 'comp') | (group_train.category == 'rec') | (group_train.category == 'politics') | (group_train.category == 'religion')]
group_test_category = group_test[(group_test.category == 'comp') | (group_test.category == 'rec') | (group_test.category == 'politics') | (group_test.category == 'religion')]



# # spliting data into input X_train and output Y_train
# X_train = group_train_category.review
# # Y_train = group_train_category.category

# # spliting data into input X_train and output Y_train
# X_test = group_test_category.review
# # Y_test = group_test_category.category

# print(X_train.shape)
# print(X_test.shape)
# group_train_category.head()

In [35]:
# group_train_category['category_num'] = group_train_category.category.map({'comp':0, 'rec':1, 'politics':2, 'religion':3})
# group_test_category['category_num'] = group_test_category.category.map({'comp':0, 'rec':1, 'politics':2, 'religion':3})

group_train_test_category = pd.concat([group_train_category, group_test_category])

In [36]:
print(group_train_category.shape)
print(group_test_category.shape)
print(group_train_test_category.shape)

(7876, 4)
(5244, 4)
(13120, 4)


In [37]:
import numpy as np
from keras.utils import np_utils

from sklearn.preprocessing import LabelEncoder

Label_encoded = LabelEncoder()
Y_label_encoded = Label_encoded.fit_transform(group_train_test_category['category'].values)
Y = np_utils.to_categorical(Y_label_encoded)
X = group_train_test_category.review

# Y_test_label_encoded = np_utils.to_categorical(np.asarray(group_test_category['category']))


print(Y.shape)
print(X.shape)
print(Y_label_encoded)
print(Y)

# from sklearn.preprocessing import LabelEncoder


# Label_encoded = LabelEncoder()
# Y_train_label_encoded = Label_encoded.fit_transform(group_train_category['category'].values)
# Y_test_label_encoded = Label_encoded.fit_transform(group_test_category['category'].values)



(13120, 4)
(13120,)
[0 0 0 ..., 3 3 3]
[[ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 ..., 
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]]


In [38]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences


tokenizer = Tokenizer()
tokenizer.fit_on_texts(X)

X_sequences = tokenizer.texts_to_sequences(X)

X_word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(X_word_index))

X_data = pad_sequences(X_sequences, maxlen=500)

print('Shape of data tensor:', X_data.shape)



Found 172367 unique tokens.
Shape of data tensor: (13120, 500)


In [39]:
X_train =X_data[:10000]
X_test = X_data[10000:]
Y_train = Y[:10000]
Y_test =Y[10000:]

In [43]:
import numpy
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import Flatten
from keras.layers.convolutional import Convolution1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
from keras import losses
from keras.utils import np_utils
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

model = Sequential()
model.add(Embedding(len(X_word_index)+1, 32, input_length=500))
model.add(Convolution1D(nb_filter=32, filter_length=3, border_mode= 'same' , activation= 'relu' ))
model.add(MaxPooling1D(pool_length=2))
model.add(Flatten())
model.add(Dense(250, activation= 'relu' ))
model.add(Dense(4, activation= 'softmax' ))
model.compile(loss= 'categorical_crossentropy', optimizer= 'adam' , metrics=[ 'accuracy' ])
print(model.summary())
# Fit the model
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), nb_epoch=10, batch_size=128, verbose=1)
# Final evaluation of the model

scores = model.evaluate(X_test, Y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

C:\Users\karis\Anaconda2\envs\py3\lib\site-packages\ipykernel\__main__.py:17: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(filters=32, kernel_size=3, padding="same", activation="relu")`
C:\Users\karis\Anaconda2\envs\py3\lib\site-packages\ipykernel\__main__.py:18: UserWarning: Update your `MaxPooling1D` call to the Keras 2 API: `MaxPooling1D(pool_size=2)`


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 500, 32)           5515776   
_________________________________________________________________
conv1d_9 (Conv1D)            (None, 500, 32)           3104      
_________________________________________________________________
max_pooling1d_9 (MaxPooling1 (None, 250, 32)           0         
_________________________________________________________________
flatten_9 (Flatten)          (None, 8000)              0         
_________________________________________________________________
dense_17 (Dense)             (None, 250)               2000250   
_________________________________________________________________
dense_18 (Dense)             (None, 4)                 1004      
Total params: 7,520,134
Trainable params: 7,520,134
Non-trainable params: 0
_________________________________________________________________


C:\Users\karis\Anaconda2\envs\py3\lib\site-packages\keras\models.py:834: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 10000 samples, validate on 3120 samples
Epoch 1/10
10000/10000 [==============================] - 39s - loss: 0.9148 - acc: 0.6158 - val_loss: 0.8844 - val_acc: 0.6311

In [44]:
# import os
# import numpy as np
# embeddings_index = {}
# f = os.path.join('C:/Users/karis/Desktop/latently', 'glove.6B.100d.txt')
# with open(f,encoding='utf-8') as main:
#     for line in main:
#         values = line.split()
#         word = values[0]
#         coefs = np.asarray(values[1:], dtype='float32')
#         embeddings_index[word] = coefs


# print('Found %s word vectors.' % len(embeddings_index))

Found 400000 word vectors.


In [10]:
# embedding_matrix = np.zeros((len(X_word_index) + 1, 100))
# for word, i in X_word_index.items():
#     embedding_vector = embeddings_index.get(word)
#     if embedding_vector is not None:
#         # words not found in embedding index will be all-zeros.
#         embedding_matrix[i] = embedding_vector
